/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_nsu_chuvashov_MyJNIClass */

#ifndef _Included_ru_nsu_chuvashov_MyJNIClass
#define _Included_ru_nsu_chuvashov_MyJNIClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_nsu_chuvashov_MyJNIClass
 * Method:    devourMemoryAndKMS
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_nsu_chuvashov_MyJNIClass_devourMemoryAndKMS
  (JNIEnv *, jobject);

/*
 * Class:     ru_nsu_chuvashov_MyJNIClass
 * Method:    allocate1kb
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_nsu_chuvashov_MyJNIClass_allocate1kb
  (JNIEnv *, jobject);

/*
 * Class:     ru_nsu_chuvashov_MyJNIClass
 * Method:    brickInside
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ru_nsu_chuvashov_MyJNIClass_brickInside
  (JNIEnv *, jobject, jint);

/*
 * Class:     ru_nsu_chuvashov_MyJNIClass
 * Method:    stringLength
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ru_nsu_chuvashov_MyJNIClass_stringLength
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ru_nsu_chuvashov_MyJNIClass
 * Method:    callNigger
 * Signature: (Lru/nsu/chuvashov/SimpleBean;)V
 */
JNIEXPORT void JNICALL Java_ru_nsu_chuvashov_MyJNIClass_callNigger
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ru_nsu_chuvashov_MyJNIClass
 * Method:    changeCottonField
 * Signature: (Lru/nsu/chuvashov/SimpleBean;I)V
 */
JNIEXPORT void JNICALL Java_ru_nsu_chuvashov_MyJNIClass_changeCottonField
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     ru_nsu_chuvashov_MyJNIClass
 * Method:    allocSwag
 * Signature: (ID)J
 */
JNIEXPORT jlong JNICALL Java_ru_nsu_chuvashov_MyJNIClass_allocSwag
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     ru_nsu_chuvashov_MyJNIClass
 * Method:    readSwag
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_nsu_chuvashov_MyJNIClass_readSwag
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ru_nsu_chuvashov_MyJNIClass
 * Method:    freeSwag
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ru_nsu_chuvashov_MyJNIClass_freeSwag
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
