/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_nsu_chuvashov_JNIMatrixMul */

#ifndef _Included_ru_nsu_chuvashov_JNIMatrixMul
#define _Included_ru_nsu_chuvashov_JNIMatrixMul
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_nsu_chuvashov_JNIMatrixMul
 * Method:    multiply
 * Signature: ([D[DI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ru_nsu_chuvashov_JNIMatrixMul_multiply
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
